apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-0
spec:
  capacity:
    storage: 3G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/mysql-0

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-1
spec:
  capacity:
    storage: 3G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/mysql-1


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-2
spec:
  capacity:
    storage: 3G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/mysql-2
