apiVersion: v1
kind: Pod
metadata:
  name: test-project-volume
spec:
  containers:
    - name: test-secret
      image: busybox
      args:
        - sleep
        - "86400"
      volumeMounts:
        - mountPath: "/projected-volume"
          name: mysql-cred
          readOnly: true
  volumes:
    - name: mysql-cred
      projected:
        sources:
          - secret:
              name: user
          - secret:
              name: pass