apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
    - name: kubia
      image: luksa/kubia-unhealthy
      livenessProbe:
        httpGet:
          port: 8080
          path: /
        initialDelaySeconds: 15
        timeoutSeconds: 4
        periodSeconds: 3
        failureThreshold: 5
