apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  labels:
    app: zk
spec:
  ports:
    # 数据同步
    - port: 2888
      name: server
    # 选举
    - port: 3888
      name: leader-election
  # headless service
  clusterIP: None
  selector:
    app: zk

---

apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  labels:
    app: zk
spec:
  ports:
    # 客户端访问
    - port: 2181
      name: client
  selector:
    app: zk

---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
spec:
  selector:
    matchLabels:
      app: zk
  maxUnavailable: 1

---
## zoo.cfg 和 myid 都是自动生成的

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
spec:
  selector:
    matchLabels:
      app: zk
  # 这里和 headless service 同名
  serviceName: zk-hs
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: zk
    spec:
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            - topologyKey: kubernetes.io/hostname
#              labelSelector:
#                matchExpressions:
#                  - key: app
#                    operator: in
#                    values:
#                      - zk
      containers:
        - name: kubernetes-zookeeper
          imagePullPolicy: IfNotPresent
          image: k8s.gcr.io/kubernetes-zookeeper:1.0-3.4.10
          resources:
            requests:
              cpu: 0.1
              memory: 500Mi
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
          command:
            - sh
            - -c
            - "start-zookeeper \
                     --servers=3 \
                     --data_dir=/var/lib/zookeeper/data \
                     --data_log_dir=/var/lib/zookeeper/data/log \
                     --conf_dir=/opt/zookeeper/conf \
                     --client_port=2181 \
                     --election_port=3888 \
                     --server_port=2888 \
                     --tick_time=2000 \
                     --init_limit=10 \
                     --sync_limit=5 \
                     --heap=512M \
                     --max_client_cnxns=60 \
                     --snap_retain_count=3 \
                     --purge_interval=12 \
                     --max_session_timeout=40000 \
                     --min_session_timeout=4000 \
                     --log_level=INFO"
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - zookeeper-ready 2181
            initialDelaySeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - zookeeper-ready 2181
            initialDelaySeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /var/lib/zookeeper
              name: datadir
#      securityContext:
#        runAsUser: 1000
#        fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 200Mi

