apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-0
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/zookeeper-0

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-1
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/zookeeper-1


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-2
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/zookeeper-2
