
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: es
  labels:
    app: kibana
spec:
  ports:
    - port: 5601
      nodePort: 31601
  type: NodePort
  selector:
    app: kibana

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: es
  name: kibana
  labels:
    app: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:7.4.0
#          resources:
#            limits:
#              memory: 500Mi
          env:
            # 这个参数并没有什么卵用，后续看一波文档
            - name: "ELASTICSEARCH_URL"
              value: "http://es-out:9200"
          ports:
            - containerPort: 5601