apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-chown
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: grafana-chown
          command: ["chown", "-R", "472:472", "/var/lib/grafana"]
          image: busybox
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: storage
              mountPath: /var/lib/grafana
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: grafana