apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:5.3.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: grafana
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin321
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
#          resources:
#            limits:
#              cpu: 100m
#              memory: 256Mi
#            requests:
#              cpu: 100m
#              memory: 256Mi
          volumeMounts:
            - mountPath: /var/lib/grafana
#              subPath: grafana
              name: storage
            - mountPath: "/etc/grafana"
              name: config
      securityContext:
        fsGroup: 472
        runAsUser: 472
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: grafana
        - name: config
          configMap:
            name: grafana-config