
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: kube-ops
data:
  grafana.ini: |
    [server]
    root_url = http://grafana.neeson.top
    [smtp]
    enabled = true
    host = smtp.163.com:25
    user = 1034458774@163.com
    password =
    skip_verify = true
    from_address = 1034458774@163.com
    [alerting]
    enabled = true
    execute_alerts = true