apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-lamp-site-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/lamp

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-lamp-site-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
