apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv-0
  labels:
    app: es
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
#  storageClassName: es-data-db
  hostPath:
    path: /tmp/es-0

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv-1
  labels:
    app: es
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
#  storageClassName: es-data-db
  hostPath:
    path: /tmp/es-1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv-2
  labels:
    app: es
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
#  storageClassName: es-data-db
  hostPath:
    path: /tmp/es-2
