apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongodb-2
spec:
    capacity:
        storage: 100Mi
    accessModes:
        - ReadWriteOnce
        - ReadOnlyMany
    hostPath:
        path: /tmp/mongodb2