apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-0
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/redis-0

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-1
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/redis-1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-2
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/redis-2

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-3
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/redis-3

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-4
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/redis-4


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-5
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/redis-5
