apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-0
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/redis-0

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-1
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/redis-1
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-0
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/redis-0

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-2
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/redis-2
