apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      name: redis-port
  clusterIP: None
  selector:
    app: redis
    appCluster: redis-cluster

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-app
spec:
  selector:
    matchLabels:
      app: redis
      appCluster: redis-cluster
  serviceName: redis-service
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
        appCluster: redis-cluster
    spec:
      containers:
        - name: redis
          image: redis
          command:
            - redis-server
          args:
            - /etc/redis/redis.conf
            - --protected-mode
            - no
          resources:
            requests:
              cpu: 0.1
              memory: 100Mi
          ports:
            - containerPort: 6379
              name: redis
            - containerPort: 16379
              name: cluster
          volumeMounts:
            - mountPath: /etc/redis
              name: redis-conf
            - mountPath: /var/lib/redis
              name: redis-data
      volumes:
        - name: redis-conf
          configMap:
            name: redis-conf
            items:
              - key: redis.conf
                path: redis.conf
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 200Mi